/* =========================================================
   MAISON KAGE · Clases de Tailwind de los componentes
   Las plantillas de js/ usan estos nombres, por ejemplo TW.btnGold.
   Los colores y tipografías salen de js/tailwind.config.js
   ========================================================= */
const TW = {
  tagLink: "inline-block border border-navy py-1 px-3 text-[14px] font-semibold bg-ivory no-underline hover:underline hover:bg-smoke",
  crossLink: "mt-4 text-[15px]",
  decAsk: "bg-ivory border border-navy p-6 self-center",
  decAskTitle: "font-serif font-semibold text-[22px] leading-[normal] uppercase tracking-[.1em] mb-2",
  priceFrom: "font-sans font-semibold text-[13px] leading-[normal]",
  decSizes: "flex gap-[6px] flex-wrap mt-1",
  decSize: "border border-navy py-[2px] px-2 text-[12px] font-semibold bg-ivory",
  tabsWrap: "mt-14",
  tabList: "flex gap-2 border-b border-smoke",
  tab: "py-3 px-6 -mb-px font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase cursor-pointer bg-ivory text-navy border border-transparent hover:underline aria-selected:border-navy aria-selected:border-b-ivory aria-selected:hover:no-underline movil:px-4",
  tabPanel: "pt-6 max-w-[80ch] text-[16px] focus:outline-none",
  usoList: "list-decimal ml-5 grid gap-2 mt-4",
  usoNote: "mt-4 bg-smoke py-3 px-4 text-[14px]",
  cardMediaLink: "block relative mb-3 cursor-pointer hover:ring-2 hover:ring-gold",
  deliveryBox: "border border-navy border-l-8 border-l-gold py-4 px-5 bg-ivory text-left grid gap-1 text-[15px] mt-4",
  deliveryTitle: "flex items-center gap-2 font-bold [&_svg]:w-5 [&_svg]:h-5 [&_svg]:shrink-0",
  guiaLabel: "mt-2 text-[12px] font-bold uppercase tracking-[.1em]",
  guiaRow: "flex flex-wrap items-center gap-3 [&_svg]:w-4 [&_svg]:h-4",
  guiaNum: "font-sans font-extrabold text-[22px] tracking-[.06em] tabular-nums mr-2",
  storeInfo: "bg-smoke py-3 px-4 text-[14px] grid gap-1 mt-1",
  body: "font-sans bg-ivory text-navy text-[16px] leading-[1.55]",
  skip: "absolute left-4 -top-20 z-[200] bg-gold text-navy py-3 px-[18px] font-bold no-underline focus:top-3",
  wrap: "max-w-[1240px] mx-auto px-8 laptop:px-6 movil:px-4",
  main: "block min-h-[70vh] focus:outline-none pt-9 pb-20 movil:pt-6 movil:pb-14",
  block: "mt-14",
  center: "text-center mx-auto",
  pageTitle: "font-serif uppercase font-semibold tracking-[.12em] leading-[1.15] movil:tracking-[.08em] text-[38px] tablet:text-[32px] movil:text-[26px]",
  pageTitleFocus: "font-serif uppercase font-semibold tracking-[.12em] leading-[1.15] movil:tracking-[.08em] text-[38px] tablet:text-[32px] movil:text-[26px] focus:outline-none",
  sectionTitle: "font-serif uppercase font-semibold text-[24px] tracking-[.14em] flex justify-between items-baseline gap-4 border-b border-smoke pb-3 mb-7 movil:text-[19px] movil:flex-wrap",
  sectionLink: "font-sans font-semibold text-[14px] leading-[normal] tracking-[.02em] normal-case underline",
  h2Serif: "font-serif uppercase font-semibold text-[28px] tracking-[.12em] leading-[1.2]",
  miniTitle: "font-serif uppercase font-semibold text-[16px] tracking-[.16em] mb-[10px]",
  eyebrow: "font-sans font-bold text-[12px] leading-[normal] tracking-[.16em] uppercase",
  eyebrowRule: "font-sans font-bold text-[12px] leading-[normal] tracking-[.16em] uppercase flex items-center gap-3 before:content-[''] before:w-9 before:h-[2px] before:bg-gold",
  lead: "text-[18px] max-w-[52ch] movil:text-[16px]",
  small: "text-[14px]",
  link: "underline",
  linkSmall: "text-[14px] underline",
  btnGold: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-gold text-navy border-gold hover:bg-navy hover:text-ivory hover:border-navy",
  btnOutline: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-ivory text-navy border-navy hover:bg-navy hover:text-ivory",
  btnNavy: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-navy text-ivory border-navy hover:bg-gold hover:text-navy hover:border-gold",
  btnText: "bg-transparent border-0 p-0 font-sans font-semibold text-[14px] leading-[normal] underline cursor-pointer text-navy hover:text-red",
  btnRow: "flex gap-3 flex-wrap",
  btnRowCenter: "flex gap-3 flex-wrap justify-center",
  ph: "bg-smoke border border-navy relative aspect-square w-full",
  phWide: "bg-smoke border border-navy relative aspect-[4/3] w-full",
  phQr: "bg-smoke border border-navy relative aspect-square w-[180px] my-3 mx-auto movil:w-[150px]",
  phLogo: "bg-smoke border border-navy relative aspect-[3/2] w-16",
  phSvg: "absolute inset-0 w-full h-full stroke-navy stroke-1",
  phImg: "absolute inset-0 w-full h-full object-cover bg-ivory",
  grid: "grid grid-cols-4 gap-6 laptop:grid-cols-3 movil:grid-cols-2 movil:gap-3",
  grid3: "grid grid-cols-3 gap-6 laptop:grid-cols-2 movil:grid-cols-2 movil:gap-3",
  card: "bg-ivory border border-smoke p-4 flex flex-col gap-1 relative hover:border-navy movil:p-[10px]",
  cardMedia: "relative mb-3",
  cardSeal: "rounded-full bg-red text-ivory grid place-items-center font-sans font-extrabold leading-[normal] border-[3px] border-double border-ivory shadow-[0_0_0_2px_theme(colors.red)] absolute top-[10px] left-[10px] w-[58px] h-[58px] text-[14px] movil:w-[46px] movil:h-[46px] movil:text-[12px] movil:top-[6px] movil:left-[6px]",
  sealInline: "rounded-full bg-red text-ivory grid place-items-center font-sans font-extrabold leading-[normal] border-[3px] border-double border-ivory shadow-[0_0_0_2px_theme(colors.red)] inline-grid align-middle w-[52px] h-[52px] text-[13px]",
  sealBig: "rounded-full bg-red text-ivory grid place-items-center font-sans font-extrabold leading-[normal] border-[3px] border-double border-ivory shadow-[0_0_0_2px_theme(colors.red)] w-24 h-24 mx-auto mb-[18px] text-[36px]",
  sealWait: "rounded-full bg-navy text-ivory grid place-items-center font-sans font-extrabold leading-[normal] border-[3px] border-double border-ivory shadow-[0_0_0_2px_theme(colors.navy)] w-24 h-24 mx-auto mb-[18px] text-[36px]",
  cardTag: "absolute bottom-[10px] left-[10px] inline-block font-sans font-bold text-[11px] leading-[normal] tracking-[.1em] uppercase py-1 px-2 bg-navy text-ivory",
  cardTagGold: "absolute bottom-[10px] left-[10px] inline-block font-sans font-bold text-[11px] leading-[normal] tracking-[.1em] uppercase py-1 px-2 bg-gold text-navy",
  fav: "rounded-full bg-ivory border border-navy text-navy grid place-items-center cursor-pointer hover:bg-navy hover:text-ivory [&_svg]:w-5 [&_svg]:h-5 [&_svg]:fill-ivory [&:hover_svg]:fill-navy aria-pressed:!text-red aria-pressed:!border-red [&[aria-pressed=true]_svg]:!fill-red aria-pressed:hover:!bg-ivory absolute top-[10px] right-[10px] w-10 h-10 movil:w-9 movil:h-9 movil:top-[6px] movil:right-[6px]",
  favInline: "rounded-full bg-ivory border border-navy text-navy grid place-items-center cursor-pointer hover:bg-navy hover:text-ivory [&_svg]:w-5 [&_svg]:h-5 [&_svg]:fill-ivory [&:hover_svg]:fill-navy aria-pressed:!text-red aria-pressed:!border-red [&[aria-pressed=true]_svg]:!fill-red aria-pressed:hover:!bg-ivory static w-[46px] h-[46px] !rounded-none",
  cardBrand: "font-sans font-bold text-[12px] leading-[normal] tracking-[.12em] uppercase",
  cardName: "font-serif uppercase font-semibold text-[21px] tracking-[.1em] leading-[1.15] movil:text-[17px]",
  cardNameLink: "no-underline hover:underline",
  cardMeta: "text-[14px]",
  price: "font-sans font-extrabold text-[19px] leading-[normal] movil:text-[17px]",
  priceOld: "font-normal text-[14px] ml-[6px]",
  priceUnit: "font-sans font-medium text-[13px] leading-[normal] ml-1",
  cardDec: "text-[13px] border-t border-smoke pt-2 mt-[6px] flex items-center gap-[6px] [&_svg]:w-[14px] [&_svg]:h-[14px]",
  cardBtn: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-gold text-navy border-gold hover:bg-navy hover:text-ivory hover:border-navy mt-3 movil:px-[10px] movil:text-[12px]",
  crumbs: "flex flex-wrap gap-[6px] text-[14px] mb-5",
  crumb: "before:content-['/'] before:mr-[6px] first:before:content-none aria-[current=page]:font-bold",
  pageHead: "mb-7",
  pageHeadP: "mt-2 max-w-[70ch]",
  pageIntro: "mt-2 mb-6",
  hero: "grid grid-cols-[1.05fr_1fr] gap-14 items-center pt-6 pb-12 border-b border-smoke tablet:grid-cols-1 tablet:gap-7",
  heroTitle: "font-serif uppercase font-semibold tracking-[.12em] leading-[1.15] movil:tracking-[.08em] text-[46px] mt-[14px] mb-4 tablet:text-[38px] movil:text-[30px]",
  heroBtns: "flex gap-3 flex-wrap mt-7",
  heroNote: "mt-[18px] text-[14px] flex gap-[18px] movil:flex-col movil:gap-[6px]",
  heroNoteItem: "flex items-center gap-[6px] [&_svg]:w-4 [&_svg]:h-4",
  catalog: "grid grid-cols-[250px_1fr] gap-10 items-start tablet:grid-cols-1 tablet:gap-7",
  filters: "sticky top-[112px] tablet:static tablet:hidden tablet:border tablet:border-navy tablet:p-4 tablet:mb-2",
  fToggle: "hidden tablet:inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-ivory text-navy border-navy hover:bg-navy hover:text-ivory justify-self-start",
  filtersHead: "flex justify-between items-center mb-2",
  filtersTitle: "font-serif uppercase font-semibold text-[16px] tracking-[.16em] m-0",
  fieldset: "border-0 border-t border-smoke pt-4 pb-[14px]",
  legend: "font-serif font-semibold text-[15px] leading-[normal] uppercase tracking-[.16em] pb-2 float-left w-full",
  check: "flex items-center gap-[10px] py-[5px] text-[15px] cursor-pointer clear-both",
  checkInput: "w-[18px] h-[18px] accent-navy shrink-0",
  checkN: "ml-auto text-[13px]",
  toolbar: "flex justify-between items-center gap-4 border-b border-smoke pb-[14px] mb-[14px] movil:flex-col movil:items-start",
  count: "font-bold focus:outline focus:outline-[3px] focus:outline-red focus:outline-offset-4",
  sort: "flex items-center gap-[10px] text-[14px] font-semibold",
  chips: "flex flex-wrap gap-2 mb-[22px] min-h-[8px]",
  chip: "inline-flex items-center gap-2 border border-navy py-[6px] px-3 font-sans font-semibold text-[13px] leading-[normal] cursor-pointer hover:bg-gold hover:text-navy hover:border-gold bg-navy text-ivory",
  chipLight: "inline-flex items-center gap-2 border border-navy py-[6px] px-3 font-sans font-semibold text-[13px] leading-[normal] cursor-pointer hover:bg-gold hover:text-navy hover:border-gold bg-ivory text-navy underline",
  suggest: "flex gap-2 justify-center flex-wrap mt-3",
  field: "flex flex-col gap-[6px] mb-[18px]",
  fieldTight: "flex flex-col gap-[6px] mb-[14px]",
  label: "font-sans font-bold text-[14px] leading-[normal]",
  req: "text-red",
  optTag: "font-normal",
  help: "text-[13px]",
  input: "h-[46px] border-0 border-b-2 border-navy bg-smoke text-navy px-3 font-sans font-normal text-[15px] leading-[normal] w-full aria-[invalid=true]:!border-2 aria-[invalid=true]:!border-red",
  select: "h-[46px] border-0 border-b-2 border-navy bg-smoke text-navy px-3 font-sans font-normal text-[15px] leading-[normal] w-full aria-[invalid=true]:!border-2 aria-[invalid=true]:!border-red cursor-pointer",
  errorMsg: "text-red font-sans font-bold text-[14px] leading-[normal] flex gap-[6px] items-center before:content-['!'] before:inline-grid before:place-items-center before:w-[18px] before:h-[18px] before:rounded-full before:bg-red before:text-ivory before:text-[12px] before:shrink-0",
  errSummary: "border-2 border-red py-4 px-[18px] mb-[22px] bg-ivory",
  errSummaryTitle: "font-sans font-extrabold text-[16px] leading-[normal] text-red mb-[6px]",
  errSummaryItem: "list-disc ml-[18px]",
  errSummaryBtn: "align-top bg-transparent border-0 font-sans font-semibold text-[15px] leading-[normal] underline cursor-pointer text-navy text-left",
  okBox: "border-2 border-navy border-l-8 border-l-gold py-[18px] px-5 bg-ivory",
  reqNote: "text-[13px] mb-[18px]",
  two: "grid grid-cols-2 gap-x-5 movil:grid-cols-1",
  twoKeep: "grid grid-cols-2 gap-x-5",
  passWrap: "flex",
  passInput: "h-[46px] border-0 border-b-2 border-navy bg-smoke text-navy px-3 font-sans font-normal text-[15px] leading-[normal] w-full aria-[invalid=true]:!border-2 aria-[invalid=true]:!border-red flex-1",
  passBtn: "border-0 border-b-2 border-navy bg-navy text-ivory px-[14px] font-sans font-bold text-[12px] leading-[normal] tracking-[.08em] uppercase cursor-pointer hover:bg-gold hover:text-navy",
  checkLine: "flex gap-[10px] items-start text-[14px] mb-3 cursor-pointer",
  checkLineInput: "w-[18px] h-[18px] mt-[2px] accent-navy shrink-0",
  opts: "border-0 flex gap-3 flex-wrap my-[18px]",
  optsTop: "border-0 flex gap-3 flex-wrap mb-[18px]",
  optsLegend: "font-sans font-bold text-[14px] leading-[normal] mb-2 w-full",
  opt: "group cursor-pointer",
  optInput: "sr-only peer",
  optBox: "flex flex-col items-start min-w-[120px] border border-navy py-[10px] px-4 bg-ivory movil:min-w-[96px] movil:py-2 movil:px-3 group-hover:border-2 group-hover:py-[9px] group-hover:px-[15px] peer-checked:bg-navy peer-checked:text-ivory peer-checked:shadow-[inset_0_-4px_0_theme(colors.gold)] peer-focus-visible:outline peer-focus-visible:outline-[3px] peer-focus-visible:outline-red peer-focus-visible:outline-offset-[3px]",
  optStrong: "text-[16px]",
  optSmall: "text-[14px]",
  optEm: "not-italic text-[12px]",
  stepper: "inline-flex border border-navy bg-ivory",
  stepperBtn: "w-10 h-11 border-0 bg-ivory font-sans font-semibold text-[20px] leading-[normal] cursor-pointer hover:bg-navy hover:text-ivory disabled:bg-smoke disabled:text-navy disabled:cursor-not-allowed",
  stepperOut: "w-[46px] grid place-items-center font-bold border-x border-smoke",
  stock: "text-[14px] font-semibold",
  stockAlert: "text-[14px] font-semibold text-red",
  alert: "text-red",
  pd: "grid grid-cols-2 gap-14 tablet:grid-cols-1 tablet:gap-7",
  thumbs: "grid grid-cols-3 gap-3 mt-3 max-w-[75%]",
  thumb: "border-2 border-ivory bg-ivory p-[2px] cursor-pointer aria-pressed:border-gold hover:!border-navy",
  galleryCap: "text-[13px] mt-2",
  pdName: "font-serif uppercase font-semibold text-[44px] tracking-[.12em] leading-[1.1] mt-2 mb-[6px] tablet:text-[36px] movil:text-[30px]",
  pdMeta: "text-[15px]",
  pdPrice: "flex items-center gap-[14px] mt-[18px]",
  priceLg: "font-sans font-extrabold text-[30px] leading-[normal] movil:text-[24px]",
  qtyRow: "flex items-center gap-4 flex-wrap",
  pdActions: "flex gap-3 mt-[22px] flex-wrap",
  pdBtnGold: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-gold text-navy border-gold hover:bg-navy hover:text-ivory hover:border-navy flex-1 min-w-[180px] movil:min-w-0 movil:basis-full",
  pdBtnOutline: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-ivory text-navy border-navy hover:bg-navy hover:text-ivory flex-1 min-w-[180px] movil:min-w-0 movil:basis-full",
  pdBtnNavy: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-navy text-ivory border-navy hover:bg-gold hover:text-navy hover:border-gold flex-1 min-w-[180px] movil:min-w-0 movil:basis-full",
  pdOcc: "mt-7",
  tags: "flex gap-2 flex-wrap",
  tagItem: "border border-navy py-1 px-3 text-[14px] font-semibold bg-ivory",
  perks: "mt-[26px] border-t border-smoke pt-4 grid gap-[6px] text-[14px]",
  perk: "flex gap-2 items-center [&_svg]:w-4 [&_svg]:h-4",
  pdDetails: "grid grid-cols-[1.2fr_1fr] gap-14 mt-14 tablet:grid-cols-1 tablet:gap-7 tablet:mt-10",
  pyramid: "grid gap-[14px]",
  pyr: "grid grid-cols-[110px_1fr] gap-4 border-b border-smoke pb-[14px] movil:grid-cols-1 movil:gap-1",
  pyrTitle: "font-serif font-semibold text-[16px] leading-[normal] uppercase tracking-[.16em]",
  pyrText: "text-[15px]",
  pyrHint: "text-[13px]",
  accords: "grid gap-[14px]",
  accord: "grid grid-cols-[150px_1fr] items-center gap-[14px] font-semibold text-[15px] movil:grid-cols-[110px_1fr]",
  meter: "h-3 bg-smoke block",
  meterFill: "block h-full bg-navy",
  decantBand: "bg-smoke border-t-[3px] border-gold mt-14 py-9 px-10 tablet:py-7 tablet:px-6",
  decGrid: "grid grid-cols-[1fr_1.1fr] gap-12 items-start tablet:grid-cols-1 tablet:gap-7",
  decTitle: "font-serif uppercase font-semibold text-[28px] tracking-[.12em] leading-[1.2] mt-[10px] mb-3",
  decFacts: "flex gap-x-5 gap-y-2 mt-4 flex-wrap",
  decFact: "flex items-center gap-2 text-[14px] font-semibold [&_svg]:w-4 [&_svg]:h-4",
  decNote: "text-[14px] mt-[10px]",
  cart: "grid grid-cols-[1fr_370px] gap-12 items-start laptop:grid-cols-[1fr_320px] laptop:gap-8 tablet:grid-cols-1 tablet:gap-7",
  lines: "border-t border-navy",
  line: "grid grid-cols-[88px_1fr_90px_auto_100px_46px] gap-5 items-center py-5 border-b border-smoke laptop:grid-cols-[72px_1fr_auto_46px] laptop:[grid-template-areas:'img_info_total_rm'_'img_unit_qty_qty'] laptop:gap-x-4 laptop:gap-y-[10px] movil:grid-cols-[64px_1fr_minmax(44px,auto)] movil:[grid-template-areas:'img_info_rm'_'unit_qty_total'] movil:gap-x-3",
  lineImg: "laptop:[grid-area:img]",
  lineInfo: "laptop:[grid-area:info]",
  lineUnit: "laptop:[grid-area:unit]",
  lineQty: "inline-flex border border-navy bg-ivory laptop:[grid-area:qty] laptop:justify-self-end movil:justify-self-center",
  lineTotal: "font-extrabold text-right laptop:[grid-area:total]",
  lineRm: "w-11 h-11 border border-navy bg-ivory grid place-items-center cursor-pointer hover:bg-red hover:text-ivory hover:border-red [&_svg]:w-5 [&_svg]:h-5 laptop:[grid-area:rm]",
  lineName: "font-serif font-semibold text-[20px] leading-[normal] uppercase tracking-[.1em] movil:text-[17px]",
  summary: "border border-navy p-6 bg-ivory sticky top-[112px] tablet:static movil:p-[18px]",
  summaryTitle: "font-serif font-semibold text-[20px] leading-[normal] uppercase tracking-[.14em] mb-4",
  summaryBtnGold: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-gold text-navy border-gold hover:bg-navy hover:text-ivory hover:border-navy w-full mt-4",
  summaryBtnOutline: "inline-flex items-center justify-center gap-2 min-h-[46px] px-[22px] font-sans font-bold text-[13px] leading-[normal] tracking-[.1em] uppercase no-underline cursor-pointer border border-solid disabled:bg-smoke disabled:text-navy disabled:border-smoke disabled:cursor-not-allowed disabled:line-through bg-ivory text-navy border-navy hover:bg-navy hover:text-ivory w-full mt-[10px]",
  srow: "flex justify-between gap-3 py-[6px] text-[15px]",
  srowTotal: "flex justify-between gap-3 pb-[6px] pt-[14px] mt-[10px] border-t border-navy font-sans font-extrabold text-[20px] leading-[normal]",
  shipHint: "bg-smoke py-[10px] px-3 text-[14px] my-3",
  sumItems: "border-b border-smoke pb-3 mb-2",
  sumItem: "flex justify-between gap-3 text-[14px] py-[5px]",
  secure: "flex gap-2 items-center text-[13px] mt-3 [&_svg]:w-4 [&_svg]:h-4 [&_svg]:shrink-0",
  steps: "flex gap-7 mb-[30px] movil:gap-3 movil:flex-wrap",
  stepsCenter: "flex gap-7 mb-[30px] justify-center movil:gap-3 movil:flex-wrap",
  step: "group flex items-center gap-[10px] font-semibold text-[15px] aria-[current=step]:font-extrabold movil:text-[13px] movil:gap-[6px]",
  dot: "rounded-full grid place-items-center font-extrabold border border-navy bg-smoke shrink-0 group-data-[done]:bg-navy group-data-[done]:text-ivory group-aria-[current=step]:bg-gold group-aria-[current=step]:text-navy group-aria-[current=step]:border-gold w-[30px] h-[30px] text-[14px]",
  coGrid: "grid grid-cols-[1fr_380px] gap-12 items-start tablet:grid-cols-1 tablet:gap-7",
  coSection: "border border-smoke py-6 px-[26px] mb-[22px] movil:py-[18px] movil:px-4",
  coTitle: "font-serif font-semibold text-[20px] leading-[normal] uppercase tracking-[.14em] mb-4",
  pay: "border-0 grid gap-3",
  payOpt: "grid grid-cols-[22px_1fr_64px] gap-[14px] items-center border border-navy p-4 cursor-pointer bg-ivory has-[:checked]:border-2 has-[:checked]:shadow-[inset_6px_0_0_theme(colors.gold)]",
  payInput: "w-5 h-5 accent-navy",
  payStrong: "block",
  payText: "text-[14px]",
  empty: "text-center max-w-[600px] mx-auto my-6 py-12 px-9 border border-navy bg-ivory movil:py-8 movil:px-[18px]",
  emptyIcon: "w-[84px] h-[84px] rounded-full border-2 border-gold grid place-items-center mx-auto mb-[18px] bg-ivory [&_svg]:w-[38px] [&_svg]:h-[38px]",
  emptyTitle: "font-serif font-semibold text-[26px] leading-[normal] uppercase tracking-[.12em] mb-[10px]",
  emptyP: "mb-2",
  emptyList: "text-left inline-grid gap-1 mt-[10px] mb-[18px]",
  emptyLi: "list-disc ml-5",
  emptyBtns: "flex gap-3 flex-wrap justify-center mt-4",
  confirm: "max-w-[760px] mx-auto text-center",
  leadCenter: "text-[18px] max-w-[52ch] movil:text-[16px] text-center mx-auto mt-[10px]",
  orderBox: "text-left border border-navy py-6 px-7 my-7 movil:p-[18px]",
  nextBox: "border-2 border-navy border-l-8 border-l-gold py-[18px] px-5 bg-ivory mt-6 text-left",
  nextList: "list-decimal mt-0 mr-0 mb-4 ml-5 grid gap-[6px]",
  dl: "grid grid-cols-[180px_1fr] gap-y-2 gap-x-4 text-[15px] movil:grid-cols-1 movil:gap-[2px]",
  dt: "font-bold",
  dd: "movil:mb-2",
  errPage: "text-center max-w-[640px] mx-auto py-6",
  errIso: "w-[120px] h-[134px] mx-auto mb-[18px] block",
  errCode: "font-sans font-bold text-[14px] leading-[normal] tracking-[.2em] uppercase mb-2",
  errBtns: "flex gap-3 flex-wrap justify-center mt-[26px]",
  account: "grid grid-cols-[250px_1fr] gap-12 items-start tablet:grid-cols-1 tablet:gap-7",
  accNav: "border border-navy tablet:flex tablet:flex-wrap tablet:border-0 tablet:border-b",
  accUser: "p-[18px] border-b border-smoke tablet:basis-full tablet:pt-0 tablet:px-0 tablet:pb-3 tablet:border-0",
  accUserName: "block font-serif font-semibold text-[18px] leading-[normal] uppercase tracking-[.12em]",
  accUserMail: "text-[13px] break-all",
  accLink: "flex items-center gap-[10px] w-full py-3 px-[18px] no-underline font-sans font-medium text-[15px] leading-[normal] bg-ivory cursor-pointer text-left border-0 border-l-4 border-ivory hover:bg-smoke hover:border-l-smoke [&_svg]:w-[18px] [&_svg]:h-[18px] [&[aria-current]]:!bg-navy [&[aria-current]]:!text-ivory [&[aria-current]]:!border-l-gold [&[aria-current]]:font-bold tablet:w-auto tablet:border-l-0 tablet:border-b-[3px] tablet:py-[10px] tablet:px-3 tablet:[&[aria-current]]:!border-b-gold",
  accHr: "border-0 border-t border-smoke tablet:hidden",
  accForm: "max-w-[640px] mt-6",
  accFormBox: "border border-smoke py-6 px-[26px] mb-[22px] movil:py-[18px] movil:px-4 max-w-[640px] mt-6",
  order: "border border-navy mb-4 bg-ivory",
  orderHead: "grid grid-cols-[1fr_auto_110px] gap-4 items-center py-4 px-5 movil:grid-cols-[1fr_auto] movil:gap-2",
  orderTitle: "font-sans font-bold text-[16px] leading-[normal]",
  orderMeta: "text-[14px]",
  orderTotal: "font-extrabold text-right text-[14px]",
  orderStatus: "movil:col-span-full movil:justify-self-start",
  orderNote: "flex gap-2 items-center px-5 pb-[14px] text-[14px] font-semibold [&_svg]:text-red [&_svg]:shrink-0",
  orderDetails: "border-t border-smoke py-3 px-5",
  orderSummary: "cursor-pointer font-semibold text-[14px]",
  orderItem: "flex justify-between text-[14px] py-[6px] border-b border-smoke",
  statusEntregado: "font-sans font-bold text-[12px] leading-[normal] tracking-[.08em] uppercase py-[5px] px-[10px] border bg-navy text-ivory border-navy",
  statusCamino: "font-sans font-bold text-[12px] leading-[normal] tracking-[.08em] uppercase py-[5px] px-[10px] border bg-gold text-navy border-gold",
  statusPrep: "font-sans font-bold text-[12px] leading-[normal] tracking-[.08em] uppercase py-[5px] px-[10px] border bg-smoke text-navy border-navy",
  statusVerif: "font-sans font-bold text-[12px] leading-[normal] tracking-[.08em] uppercase py-[5px] px-[10px] border bg-ivory text-red border-red",
  addrList: "grid grid-cols-2 gap-4 mb-[22px] movil:grid-cols-1",
  addr: "border border-navy py-[18px] px-5 bg-ivory",
  addrTitle: "font-sans font-bold text-[16px] leading-[normal] flex justify-between items-center gap-[10px] mb-[6px]",
  addrText: "text-[14px]",
  addrBtns: "flex gap-4 flex-wrap mt-3",
  addrEmpty: "border border-dashed border-navy py-[18px] px-5 col-span-full",
  helpCard: "border border-smoke py-[18px] px-5 mt-7 flex justify-between items-center gap-4 movil:flex-col movil:items-start",
  helpGrid: "grid grid-cols-[1.4fr_1fr] gap-12 items-start tablet:grid-cols-1 tablet:gap-7",
  faqItem: "border-b border-smoke py-4",
  faqQ: "cursor-pointer font-bold text-[17px]",
  faqA: "mt-2 max-w-[65ch]",
  contact: "border border-navy p-[22px]",
  contactItem: "py-[10px] border-b border-smoke text-[15px]",
  auth: "max-w-[470px] mx-auto border border-navy py-9 px-10 bg-ivory movil:py-6 movil:px-[18px] movil:border-0",
  authIso: "w-[62px] h-[70px] mx-auto mb-3",
  authTitle: "font-serif uppercase font-semibold tracking-[.12em] leading-[1.15] movil:tracking-[.08em] text-center text-[30px] mb-[6px]",
  authSub: "text-center mb-6 text-[15px]",
  authAlt: "text-center mt-[22px] pt-[18px] border-t border-smoke text-[15px]",
  rowEnd: "flex justify-end -mt-2 mb-[18px]",
  toastRegion: "fixed right-6 bottom-6 z-[120] movil:left-4 movil:right-4 movil:bottom-4",
  toast: "bg-navy text-ivory border-l-[6px] border-gold py-4 px-[18px] min-w-[320px] max-w-[420px] grid grid-cols-[1fr_auto] gap-y-[6px] gap-x-[14px] items-start [&_:focus-visible]:outline-gold movil:min-w-0 movil:max-w-none",
  toastError: "bg-navy text-ivory border-l-[6px] border-red py-4 px-[18px] min-w-[320px] max-w-[420px] grid grid-cols-[1fr_auto] gap-y-[6px] gap-x-[14px] items-start [&_:focus-visible]:outline-gold movil:min-w-0 movil:max-w-none",
  toastText: "text-[15px] font-semibold",
  toastLink: "text-gold font-bold col-start-1 underline",
  toastX: "col-start-2 row-start-1 bg-navy text-ivory border border-ivory w-7 h-7 cursor-pointer text-[16px] leading-none hover:bg-gold hover:text-navy hover:border-gold",
  modalRoot: "fixed inset-0 grid place-items-center z-[150]",
  modal: "bg-ivory border-2 border-navy shadow-[0_0_0_8px_theme(colors.ivory),0_0_0_10px_theme(colors.gold)] w-[min(460px,92vw)] max-h-[92vh] overflow-auto py-7 px-[30px] movil:py-[22px] movil:px-[18px]",
  modalTitle: "font-serif font-semibold text-[22px] leading-[normal] uppercase tracking-[.12em] mb-[10px]",
  modalActions: "flex gap-3 justify-end mt-[22px] movil:flex-col-reverse movil:[&>button]:w-full",
  gw: "text-center",
  gwOrder: "mt-1",
  gwForm: "text-left mt-4",
  gwStatus: "font-bold mt-[10px] p-[10px] bg-smoke",
  gwData: "grid grid-cols-[1fr_auto] gap-y-[6px] gap-x-[14px] text-left text-[14px] mt-[6px] mb-[14px] border-y border-smoke py-[10px]",
  gwDt: "font-semibold",
  gwDd: "font-extrabold text-right",
  gwSteps: "grid gap-2 text-left mt-1 mb-3",
  gwStep: "group flex items-center gap-[10px] text-[14px] aria-[current=step]:font-extrabold",
  gwDot: "rounded-full grid place-items-center font-extrabold border border-navy bg-smoke shrink-0 group-data-[done]:bg-navy group-data-[done]:text-ivory group-aria-[current=step]:bg-gold group-aria-[current=step]:text-navy group-aria-[current=step]:border-gold w-[26px] h-[26px] text-[13px]",
  gwLinks: "flex justify-center gap-[18px] flex-wrap mt-3",
  ddHead: "pt-2 px-[18px] pb-[10px] font-sans font-semibold text-[13px] leading-[normal] tracking-[.06em] uppercase border-b border-smoke mb-[6px]",
  ddItem: "flex items-center gap-[10px] w-full text-left py-[11px] px-[18px] text-navy no-underline bg-ivory border-0 font-sans font-medium text-[15px] leading-[normal] cursor-pointer hover:bg-smoke [&[aria-current]]:font-bold [&[aria-current]]:shadow-[inset_3px_0_0_theme(colors.gold)] [&_svg]:w-[18px] [&_svg]:h-[18px] [&_svg]:shrink-0",
  ddHr: "border-0 border-t border-smoke my-[6px]"
};
